name: CI-CD PIPELINE
on:
  push:
    branches: [praveen]
  pull_request:
    branches: [praveen]
jobs: 
  format:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.6.0
      - name: Terraform fmt
        working-directory: terraform
        run: terraform fmt -check -recursive
